// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AgentRequest.proto

package com.github.masterdxy.light.dubbo.agent.common.model;

public final class AgentRequestOuterClass {
  private AgentRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AgentRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.masterdxy.light.dubbo.agent.common.model.AgentRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 rl = 1;</code>
     */
    boolean hasRl();
    /**
     * <code>required int64 rl = 1;</code>
     */
    long getRl();

    /**
     * <code>optional string d = 2;</code>
     */
    boolean hasD();
    /**
     * <code>optional string d = 2;</code>
     */
    String getD();
    /**
     * <code>optional string d = 2;</code>
     */
    com.google.protobuf.ByteString
        getDBytes();

    /**
     * <code>required string s = 3;</code>
     */
    boolean hasS();
    /**
     * <code>required string s = 3;</code>
     */
    String getS();
    /**
     * <code>required string s = 3;</code>
     */
    com.google.protobuf.ByteString
        getSBytes();

    /**
     * <code>required string m = 4;</code>
     */
    boolean hasM();
    /**
     * <code>required string m = 4;</code>
     */
    String getM();
    /**
     * <code>required string m = 4;</code>
     */
    com.google.protobuf.ByteString
        getMBytes();

    /**
     * <code>optional string v = 5;</code>
     */
    boolean hasV();
    /**
     * <code>optional string v = 5;</code>
     */
    String getV();
    /**
     * <code>optional string v = 5;</code>
     */
    com.google.protobuf.ByteString
        getVBytes();

    /**
     * <code>optional string ck = 6;</code>
     */
    boolean hasCk();
    /**
     * <code>optional string ck = 6;</code>
     */
    String getCk();
    /**
     * <code>optional string ck = 6;</code>
     */
    com.google.protobuf.ByteString
        getCkBytes();

    /**
     * <code>optional int64 ct = 7;</code>
     */
    boolean hasCt();
    /**
     * <code>optional int64 ct = 7;</code>
     */
    long getCt();

    /**
     * <code>optional string a = 8;</code>
     */
    boolean hasA();
    /**
     * <code>optional string a = 8;</code>
     */
    String getA();
    /**
     * <code>optional string a = 8;</code>
     */
    com.google.protobuf.ByteString
        getABytes();

    /**
     * <code>optional int64 rt = 9;</code>
     */
    boolean hasRt();
    /**
     * <code>optional int64 rt = 9;</code>
     */
    long getRt();
  }
  /**
   * Protobuf type {@code com.github.masterdxy.light.dubbo.agent.common.model.AgentRequest}
   */
  public  static final class AgentRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.github.masterdxy.light.dubbo.agent.common.model.AgentRequest)
      AgentRequestOrBuilder {
    // Use AgentRequest.newBuilder() to construct.
    private AgentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AgentRequest() {
      rl_ = 0L;
      d_ = "";
      s_ = "";
      m_ = "";
      v_ = "";
      ck_ = "";
      ct_ = 0L;
      a_ = "";
      rt_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AgentRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rl_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              d_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              s_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              m_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              v_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              ck_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              ct_ = input.readInt64();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              a_ = bs;
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              rt_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AgentRequestOuterClass.internal_static_com_github_masterdxy_light_dubbo_agent_common_model_AgentRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AgentRequestOuterClass.internal_static_com_github_masterdxy_light_dubbo_agent_common_model_AgentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AgentRequest.class, Builder.class);
    }

    private int bitField0_;
    public static final int RL_FIELD_NUMBER = 1;
    private long rl_;
    /**
     * <code>required int64 rl = 1;</code>
     */
    public boolean hasRl() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 rl = 1;</code>
     */
    public long getRl() {
      return rl_;
    }

    public static final int D_FIELD_NUMBER = 2;
    private volatile Object d_;
    /**
     * <code>optional string d = 2;</code>
     */
    public boolean hasD() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string d = 2;</code>
     */
    public String getD() {
      Object ref = d_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          d_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string d = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDBytes() {
      Object ref = d_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        d_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S_FIELD_NUMBER = 3;
    private volatile Object s_;
    /**
     * <code>required string s = 3;</code>
     */
    public boolean hasS() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string s = 3;</code>
     */
    public String getS() {
      Object ref = s_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string s = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSBytes() {
      Object ref = s_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        s_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int M_FIELD_NUMBER = 4;
    private volatile Object m_;
    /**
     * <code>required string m = 4;</code>
     */
    public boolean hasM() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string m = 4;</code>
     */
    public String getM() {
      Object ref = m_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          m_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string m = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMBytes() {
      Object ref = m_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        m_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int V_FIELD_NUMBER = 5;
    private volatile Object v_;
    /**
     * <code>optional string v = 5;</code>
     */
    public boolean hasV() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string v = 5;</code>
     */
    public String getV() {
      Object ref = v_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          v_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string v = 5;</code>
     */
    public com.google.protobuf.ByteString
        getVBytes() {
      Object ref = v_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        v_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CK_FIELD_NUMBER = 6;
    private volatile Object ck_;
    /**
     * <code>optional string ck = 6;</code>
     */
    public boolean hasCk() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string ck = 6;</code>
     */
    public String getCk() {
      Object ref = ck_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ck_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ck = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCkBytes() {
      Object ref = ck_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ck_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CT_FIELD_NUMBER = 7;
    private long ct_;
    /**
     * <code>optional int64 ct = 7;</code>
     */
    public boolean hasCt() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 ct = 7;</code>
     */
    public long getCt() {
      return ct_;
    }

    public static final int A_FIELD_NUMBER = 8;
    private volatile Object a_;
    /**
     * <code>optional string a = 8;</code>
     */
    public boolean hasA() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string a = 8;</code>
     */
    public String getA() {
      Object ref = a_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          a_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string a = 8;</code>
     */
    public com.google.protobuf.ByteString
        getABytes() {
      Object ref = a_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        a_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RT_FIELD_NUMBER = 9;
    private long rt_;
    /**
     * <code>optional int64 rt = 9;</code>
     */
    public boolean hasRt() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int64 rt = 9;</code>
     */
    public long getRt() {
      return rt_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasS()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasM()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, rl_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, d_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, s_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, m_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, v_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, ck_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, ct_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, a_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt64(9, rt_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, rl_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, d_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, s_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, m_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, v_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, ck_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, ct_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, a_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, rt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AgentRequest)) {
        return super.equals(obj);
      }
      AgentRequest other = (AgentRequest) obj;

      boolean result = true;
      result = result && (hasRl() == other.hasRl());
      if (hasRl()) {
        result = result && (getRl()
            == other.getRl());
      }
      result = result && (hasD() == other.hasD());
      if (hasD()) {
        result = result && getD()
            .equals(other.getD());
      }
      result = result && (hasS() == other.hasS());
      if (hasS()) {
        result = result && getS()
            .equals(other.getS());
      }
      result = result && (hasM() == other.hasM());
      if (hasM()) {
        result = result && getM()
            .equals(other.getM());
      }
      result = result && (hasV() == other.hasV());
      if (hasV()) {
        result = result && getV()
            .equals(other.getV());
      }
      result = result && (hasCk() == other.hasCk());
      if (hasCk()) {
        result = result && getCk()
            .equals(other.getCk());
      }
      result = result && (hasCt() == other.hasCt());
      if (hasCt()) {
        result = result && (getCt()
            == other.getCt());
      }
      result = result && (hasA() == other.hasA());
      if (hasA()) {
        result = result && getA()
            .equals(other.getA());
      }
      result = result && (hasRt() == other.hasRt());
      if (hasRt()) {
        result = result && (getRt()
            == other.getRt());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRl()) {
        hash = (37 * hash) + RL_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRl());
      }
      if (hasD()) {
        hash = (37 * hash) + D_FIELD_NUMBER;
        hash = (53 * hash) + getD().hashCode();
      }
      if (hasS()) {
        hash = (37 * hash) + S_FIELD_NUMBER;
        hash = (53 * hash) + getS().hashCode();
      }
      if (hasM()) {
        hash = (37 * hash) + M_FIELD_NUMBER;
        hash = (53 * hash) + getM().hashCode();
      }
      if (hasV()) {
        hash = (37 * hash) + V_FIELD_NUMBER;
        hash = (53 * hash) + getV().hashCode();
      }
      if (hasCk()) {
        hash = (37 * hash) + CK_FIELD_NUMBER;
        hash = (53 * hash) + getCk().hashCode();
      }
      if (hasCt()) {
        hash = (37 * hash) + CT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCt());
      }
      if (hasA()) {
        hash = (37 * hash) + A_FIELD_NUMBER;
        hash = (53 * hash) + getA().hashCode();
      }
      if (hasRt()) {
        hash = (37 * hash) + RT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRt());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AgentRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AgentRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AgentRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AgentRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AgentRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AgentRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AgentRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AgentRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AgentRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AgentRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AgentRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AgentRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AgentRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.masterdxy.light.dubbo.agent.common.model.AgentRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.masterdxy.light.dubbo.agent.common.model.AgentRequest)
        AgentRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AgentRequestOuterClass.internal_static_com_github_masterdxy_light_dubbo_agent_common_model_AgentRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AgentRequestOuterClass.internal_static_com_github_masterdxy_light_dubbo_agent_common_model_AgentRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AgentRequest.class, Builder.class);
      }

      // Construct using com.github.masterdxy.light.dubbo.agent.common.model.AgentRequestOuterClass.AgentRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        rl_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        d_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        s_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        m_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        v_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        ck_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        ct_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        a_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        rt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AgentRequestOuterClass.internal_static_com_github_masterdxy_light_dubbo_agent_common_model_AgentRequest_descriptor;
      }

      public AgentRequest getDefaultInstanceForType() {
        return AgentRequest.getDefaultInstance();
      }

      public AgentRequest build() {
        AgentRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AgentRequest buildPartial() {
        AgentRequest result = new AgentRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rl_ = rl_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.d_ = d_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.s_ = s_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.m_ = m_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.v_ = v_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.ck_ = ck_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.ct_ = ct_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.a_ = a_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.rt_ = rt_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AgentRequest) {
          return mergeFrom((AgentRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AgentRequest other) {
        if (other == AgentRequest.getDefaultInstance()) return this;
        if (other.hasRl()) {
          setRl(other.getRl());
        }
        if (other.hasD()) {
          bitField0_ |= 0x00000002;
          d_ = other.d_;
          onChanged();
        }
        if (other.hasS()) {
          bitField0_ |= 0x00000004;
          s_ = other.s_;
          onChanged();
        }
        if (other.hasM()) {
          bitField0_ |= 0x00000008;
          m_ = other.m_;
          onChanged();
        }
        if (other.hasV()) {
          bitField0_ |= 0x00000010;
          v_ = other.v_;
          onChanged();
        }
        if (other.hasCk()) {
          bitField0_ |= 0x00000020;
          ck_ = other.ck_;
          onChanged();
        }
        if (other.hasCt()) {
          setCt(other.getCt());
        }
        if (other.hasA()) {
          bitField0_ |= 0x00000080;
          a_ = other.a_;
          onChanged();
        }
        if (other.hasRt()) {
          setRt(other.getRt());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRl()) {
          return false;
        }
        if (!hasS()) {
          return false;
        }
        if (!hasM()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AgentRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AgentRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long rl_ ;
      /**
       * <code>required int64 rl = 1;</code>
       */
      public boolean hasRl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 rl = 1;</code>
       */
      public long getRl() {
        return rl_;
      }
      /**
       * <code>required int64 rl = 1;</code>
       */
      public Builder setRl(long value) {
        bitField0_ |= 0x00000001;
        rl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 rl = 1;</code>
       */
      public Builder clearRl() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rl_ = 0L;
        onChanged();
        return this;
      }

      private Object d_ = "";
      /**
       * <code>optional string d = 2;</code>
       */
      public boolean hasD() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string d = 2;</code>
       */
      public String getD() {
        Object ref = d_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            d_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string d = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDBytes() {
        Object ref = d_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          d_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string d = 2;</code>
       */
      public Builder setD(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        d_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string d = 2;</code>
       */
      public Builder clearD() {
        bitField0_ = (bitField0_ & ~0x00000002);
        d_ = getDefaultInstance().getD();
        onChanged();
        return this;
      }
      /**
       * <code>optional string d = 2;</code>
       */
      public Builder setDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        d_ = value;
        onChanged();
        return this;
      }

      private Object s_ = "";
      /**
       * <code>required string s = 3;</code>
       */
      public boolean hasS() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string s = 3;</code>
       */
      public String getS() {
        Object ref = s_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            s_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string s = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSBytes() {
        Object ref = s_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          s_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string s = 3;</code>
       */
      public Builder setS(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        s_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string s = 3;</code>
       */
      public Builder clearS() {
        bitField0_ = (bitField0_ & ~0x00000004);
        s_ = getDefaultInstance().getS();
        onChanged();
        return this;
      }
      /**
       * <code>required string s = 3;</code>
       */
      public Builder setSBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        s_ = value;
        onChanged();
        return this;
      }

      private Object m_ = "";
      /**
       * <code>required string m = 4;</code>
       */
      public boolean hasM() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string m = 4;</code>
       */
      public String getM() {
        Object ref = m_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            m_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string m = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMBytes() {
        Object ref = m_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          m_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string m = 4;</code>
       */
      public Builder setM(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        m_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string m = 4;</code>
       */
      public Builder clearM() {
        bitField0_ = (bitField0_ & ~0x00000008);
        m_ = getDefaultInstance().getM();
        onChanged();
        return this;
      }
      /**
       * <code>required string m = 4;</code>
       */
      public Builder setMBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        m_ = value;
        onChanged();
        return this;
      }

      private Object v_ = "";
      /**
       * <code>optional string v = 5;</code>
       */
      public boolean hasV() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string v = 5;</code>
       */
      public String getV() {
        Object ref = v_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            v_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string v = 5;</code>
       */
      public com.google.protobuf.ByteString
          getVBytes() {
        Object ref = v_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          v_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string v = 5;</code>
       */
      public Builder setV(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        v_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string v = 5;</code>
       */
      public Builder clearV() {
        bitField0_ = (bitField0_ & ~0x00000010);
        v_ = getDefaultInstance().getV();
        onChanged();
        return this;
      }
      /**
       * <code>optional string v = 5;</code>
       */
      public Builder setVBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        v_ = value;
        onChanged();
        return this;
      }

      private Object ck_ = "";
      /**
       * <code>optional string ck = 6;</code>
       */
      public boolean hasCk() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string ck = 6;</code>
       */
      public String getCk() {
        Object ref = ck_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ck_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string ck = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCkBytes() {
        Object ref = ck_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ck_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ck = 6;</code>
       */
      public Builder setCk(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        ck_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ck = 6;</code>
       */
      public Builder clearCk() {
        bitField0_ = (bitField0_ & ~0x00000020);
        ck_ = getDefaultInstance().getCk();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ck = 6;</code>
       */
      public Builder setCkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        ck_ = value;
        onChanged();
        return this;
      }

      private long ct_ ;
      /**
       * <code>optional int64 ct = 7;</code>
       */
      public boolean hasCt() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int64 ct = 7;</code>
       */
      public long getCt() {
        return ct_;
      }
      /**
       * <code>optional int64 ct = 7;</code>
       */
      public Builder setCt(long value) {
        bitField0_ |= 0x00000040;
        ct_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 ct = 7;</code>
       */
      public Builder clearCt() {
        bitField0_ = (bitField0_ & ~0x00000040);
        ct_ = 0L;
        onChanged();
        return this;
      }

      private Object a_ = "";
      /**
       * <code>optional string a = 8;</code>
       */
      public boolean hasA() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string a = 8;</code>
       */
      public String getA() {
        Object ref = a_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            a_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string a = 8;</code>
       */
      public com.google.protobuf.ByteString
          getABytes() {
        Object ref = a_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          a_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string a = 8;</code>
       */
      public Builder setA(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        a_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string a = 8;</code>
       */
      public Builder clearA() {
        bitField0_ = (bitField0_ & ~0x00000080);
        a_ = getDefaultInstance().getA();
        onChanged();
        return this;
      }
      /**
       * <code>optional string a = 8;</code>
       */
      public Builder setABytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        a_ = value;
        onChanged();
        return this;
      }

      private long rt_ ;
      /**
       * <code>optional int64 rt = 9;</code>
       */
      public boolean hasRt() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int64 rt = 9;</code>
       */
      public long getRt() {
        return rt_;
      }
      /**
       * <code>optional int64 rt = 9;</code>
       */
      public Builder setRt(long value) {
        bitField0_ |= 0x00000100;
        rt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 rt = 9;</code>
       */
      public Builder clearRt() {
        bitField0_ = (bitField0_ & ~0x00000100);
        rt_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.github.masterdxy.light.dubbo.agent.common.model.AgentRequest)
    }

    // @@protoc_insertion_point(class_scope:com.github.masterdxy.light.dubbo.agent.common.model.AgentRequest)
    private static final AgentRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AgentRequest();
    }

    public static AgentRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<AgentRequest>
        PARSER = new com.google.protobuf.AbstractParser<AgentRequest>() {
      public AgentRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AgentRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AgentRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AgentRequest> getParserForType() {
      return PARSER;
    }

    public AgentRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_masterdxy_light_dubbo_agent_common_model_AgentRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_masterdxy_light_dubbo_agent_common_model_AgentRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022AgentRequest.proto\022 com.github.masterdxy.light.dubbo.agent.common.model" +
      "\"u\n\014AgentRequest\022\n\n\002rl\030\001 \002" +
      "(\003\022\t\n\001d\030\002 \001(\t\022\t\n\001s\030\003 \002(\t\022\t\n\001m\030\004 \002(\t\022\t\n\001v" +
      "\030\005 \001(\t\022\n\n\002ck\030\006 \001(\t\022\n\n\002ct\030\007 \001(\003\022\t\n\001a\030\010 \001(" +
      "\t\022\n\n\002rt\030\t \001(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_github_masterdxy_light_dubbo_agent_common_model_AgentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_masterdxy_light_dubbo_agent_common_model_AgentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_masterdxy_light_dubbo_agent_common_model_AgentRequest_descriptor,
        new String[] { "Rl", "D", "S", "M", "V", "Ck", "Ct", "A", "Rt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
