// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AgentResponse.proto

package com.github.masterdxy.light.dubbo.agent.common.model;

public final class AgentResponseOuterClass {
  private AgentResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AgentResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.masterdxy.light.dubbo.agent.common.model.AgentResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 rl = 1;</code>
     */
    boolean hasRl();
    /**
     * <code>required int64 rl = 1;</code>
     */
    long getRl();

    /**
     * <code>required string d = 2;</code>
     */
    boolean hasD();
    /**
     * <code>required string d = 2;</code>
     */
    String getD();
    /**
     * <code>required string d = 2;</code>
     */
    com.google.protobuf.ByteString
        getDBytes();

    /**
     * <code>required int32 s = 3;</code>
     */
    boolean hasS();
    /**
     * <code>required int32 s = 3;</code>
     */
    int getS();

    /**
     * <code>optional string a = 4;</code>
     */
    boolean hasA();
    /**
     * <code>optional string a = 4;</code>
     */
    String getA();
    /**
     * <code>optional string a = 4;</code>
     */
    com.google.protobuf.ByteString
        getABytes();
  }
  /**
   * Protobuf type {@code com.github.masterdxy.light.dubbo.agent.common.model.AgentResponse}
   */
  public  static final class AgentResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.github.masterdxy.light.dubbo.agent.common.model.AgentResponse)
      AgentResponseOrBuilder {
    // Use AgentResponse.newBuilder() to construct.
    private AgentResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AgentResponse() {
      rl_ = 0L;
      d_ = "";
      s_ = 0;
      a_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AgentResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rl_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              d_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              s_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              a_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AgentResponseOuterClass.internal_static_com_github_masterdxy_light_dubbo_agent_common_model_AgentResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AgentResponseOuterClass.internal_static_com_github_masterdxy_light_dubbo_agent_common_model_AgentResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AgentResponse.class, Builder.class);
    }

    private int bitField0_;
    public static final int RL_FIELD_NUMBER = 1;
    private long rl_;
    /**
     * <code>required int64 rl = 1;</code>
     */
    public boolean hasRl() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 rl = 1;</code>
     */
    public long getRl() {
      return rl_;
    }

    public static final int D_FIELD_NUMBER = 2;
    private volatile Object d_;
    /**
     * <code>required string d = 2;</code>
     */
    public boolean hasD() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string d = 2;</code>
     */
    public String getD() {
      Object ref = d_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          d_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string d = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDBytes() {
      Object ref = d_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        d_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S_FIELD_NUMBER = 3;
    private int s_;
    /**
     * <code>required int32 s = 3;</code>
     */
    public boolean hasS() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 s = 3;</code>
     */
    public int getS() {
      return s_;
    }

    public static final int A_FIELD_NUMBER = 4;
    private volatile Object a_;
    /**
     * <code>optional string a = 4;</code>
     */
    public boolean hasA() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string a = 4;</code>
     */
    public String getA() {
      Object ref = a_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          a_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string a = 4;</code>
     */
    public com.google.protobuf.ByteString
        getABytes() {
      Object ref = a_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        a_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasD()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasS()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, rl_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, d_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, s_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, a_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, rl_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, d_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, s_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, a_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AgentResponse)) {
        return super.equals(obj);
      }
      AgentResponse other = (AgentResponse) obj;

      boolean result = true;
      result = result && (hasRl() == other.hasRl());
      if (hasRl()) {
        result = result && (getRl()
            == other.getRl());
      }
      result = result && (hasD() == other.hasD());
      if (hasD()) {
        result = result && getD()
            .equals(other.getD());
      }
      result = result && (hasS() == other.hasS());
      if (hasS()) {
        result = result && (getS()
            == other.getS());
      }
      result = result && (hasA() == other.hasA());
      if (hasA()) {
        result = result && getA()
            .equals(other.getA());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRl()) {
        hash = (37 * hash) + RL_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRl());
      }
      if (hasD()) {
        hash = (37 * hash) + D_FIELD_NUMBER;
        hash = (53 * hash) + getD().hashCode();
      }
      if (hasS()) {
        hash = (37 * hash) + S_FIELD_NUMBER;
        hash = (53 * hash) + getS();
      }
      if (hasA()) {
        hash = (37 * hash) + A_FIELD_NUMBER;
        hash = (53 * hash) + getA().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AgentResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AgentResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AgentResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AgentResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AgentResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AgentResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AgentResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AgentResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AgentResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AgentResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AgentResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AgentResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AgentResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.masterdxy.light.dubbo.agent.common.model.AgentResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.masterdxy.light.dubbo.agent.common.model.AgentResponse)
        AgentResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AgentResponseOuterClass.internal_static_com_github_masterdxy_light_dubbo_agent_common_model_AgentResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AgentResponseOuterClass.internal_static_com_github_masterdxy_light_dubbo_agent_common_model_AgentResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AgentResponse.class, Builder.class);
      }

      // Construct using com.github.masterdxy.light.dubbo.agent.common.model.AgentResponseOuterClass.AgentResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        rl_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        d_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        s_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        a_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AgentResponseOuterClass.internal_static_com_github_masterdxy_light_dubbo_agent_common_model_AgentResponse_descriptor;
      }

      public AgentResponse getDefaultInstanceForType() {
        return AgentResponse.getDefaultInstance();
      }

      public AgentResponse build() {
        AgentResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AgentResponse buildPartial() {
        AgentResponse result = new AgentResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rl_ = rl_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.d_ = d_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.s_ = s_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.a_ = a_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AgentResponse) {
          return mergeFrom((AgentResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AgentResponse other) {
        if (other == AgentResponse.getDefaultInstance()) return this;
        if (other.hasRl()) {
          setRl(other.getRl());
        }
        if (other.hasD()) {
          bitField0_ |= 0x00000002;
          d_ = other.d_;
          onChanged();
        }
        if (other.hasS()) {
          setS(other.getS());
        }
        if (other.hasA()) {
          bitField0_ |= 0x00000008;
          a_ = other.a_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRl()) {
          return false;
        }
        if (!hasD()) {
          return false;
        }
        if (!hasS()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AgentResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AgentResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long rl_ ;
      /**
       * <code>required int64 rl = 1;</code>
       */
      public boolean hasRl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 rl = 1;</code>
       */
      public long getRl() {
        return rl_;
      }
      /**
       * <code>required int64 rl = 1;</code>
       */
      public Builder setRl(long value) {
        bitField0_ |= 0x00000001;
        rl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 rl = 1;</code>
       */
      public Builder clearRl() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rl_ = 0L;
        onChanged();
        return this;
      }

      private Object d_ = "";
      /**
       * <code>required string d = 2;</code>
       */
      public boolean hasD() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string d = 2;</code>
       */
      public String getD() {
        Object ref = d_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            d_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string d = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDBytes() {
        Object ref = d_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          d_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string d = 2;</code>
       */
      public Builder setD(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        d_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string d = 2;</code>
       */
      public Builder clearD() {
        bitField0_ = (bitField0_ & ~0x00000002);
        d_ = getDefaultInstance().getD();
        onChanged();
        return this;
      }
      /**
       * <code>required string d = 2;</code>
       */
      public Builder setDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        d_ = value;
        onChanged();
        return this;
      }

      private int s_ ;
      /**
       * <code>required int32 s = 3;</code>
       */
      public boolean hasS() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 s = 3;</code>
       */
      public int getS() {
        return s_;
      }
      /**
       * <code>required int32 s = 3;</code>
       */
      public Builder setS(int value) {
        bitField0_ |= 0x00000004;
        s_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 s = 3;</code>
       */
      public Builder clearS() {
        bitField0_ = (bitField0_ & ~0x00000004);
        s_ = 0;
        onChanged();
        return this;
      }

      private Object a_ = "";
      /**
       * <code>optional string a = 4;</code>
       */
      public boolean hasA() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string a = 4;</code>
       */
      public String getA() {
        Object ref = a_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            a_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string a = 4;</code>
       */
      public com.google.protobuf.ByteString
          getABytes() {
        Object ref = a_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          a_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string a = 4;</code>
       */
      public Builder setA(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        a_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string a = 4;</code>
       */
      public Builder clearA() {
        bitField0_ = (bitField0_ & ~0x00000008);
        a_ = getDefaultInstance().getA();
        onChanged();
        return this;
      }
      /**
       * <code>optional string a = 4;</code>
       */
      public Builder setABytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        a_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.github.masterdxy.light.dubbo.agent.common.model.AgentResponse)
    }

    // @@protoc_insertion_point(class_scope:com.github.masterdxy.light.dubbo.agent.common.model.AgentResponse)
    private static final AgentResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AgentResponse();
    }

    public static AgentResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<AgentResponse>
        PARSER = new com.google.protobuf.AbstractParser<AgentResponse>() {
      public AgentResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AgentResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AgentResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AgentResponse> getParserForType() {
      return PARSER;
    }

    public AgentResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_masterdxy_light_dubbo_agent_common_model_AgentResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_masterdxy_light_dubbo_agent_common_model_AgentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023AgentResponse.proto\022 com.github.masterdxy.light.dubbo.agent.common.model" +
      "\"<\n\rAgentResponse\022\n\n\002rl\030\001" +
      " \002(\003\022\t\n\001d\030\002 \002(\t\022\t\n\001s\030\003 \002(\005\022\t\n\001a\030\004 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_github_masterdxy_light_dubbo_agent_common_model_AgentResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_masterdxy_light_dubbo_agent_common_model_AgentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_masterdxy_light_dubbo_agent_common_model_AgentResponse_descriptor,
        new String[] { "Rl", "D", "S", "A", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
